# schema.yml

 models:
   - name: int_orders_margin
     description: based on the orders made by the customer, we calculate the margin (revenue - purchase costs)
     columns:
       - name: orders_id
         description: orders identifiant 
         tests:
           - unique
           - not_null
       - name: date_date
         description: date at that the order has been made
       - name: revenue
         description: cumulated revenue made by order splitted by date
       - name: quantity
         description: quantity of products bought by orders & date
       - name: purchase_costs
         description: costs of sending the products by orders & date
       - name: margin
         description: calculated margin based on the revenu * quantity
   - name: int_orders_operational
     description: new table to calculate the operational margin based on the previous table
     columns:
       - name: orders_id
         description: number chain to define an order made by a customer
         tests:
           - unique
           - not_null
       - name: date_date
         description: day the client has ordered
       - name: quantity
         description: quantity of products that has been ordered for each order
       - name: operational_margin
         description: operational margin that has been calculated based on previous tables
   - name: int_sales_margin
     description: shipping & purchase costs are in this table
     columns:
       - name: orders_id
         description: number chain to define an order made by a customer
       - name: date_date
         description: day the order has been made
       - name: products_id
         description: id of the product that has been orderred
       - name: revenue
         description: revenue generated by the order
       - name: quantity
         description: quantity of product that have been ordered
       - name: purchse_price
         description: prix d'achat
       - name: purchase_costs
         description: coûts d'achat du produit
       - name: margin
         description: net margin for the company