# schema.yml

 models:
   - name: int_orders_margin
     description: based on the orders made by the customer, we calculate the margin (revenue - purchase costs)
     columns:
       - name: orders_id
         description: orders identifiant 
         tests:
           - unique
           - not_null
       - name: date_date
         description: date at that the order has been made
       - name: revenue
         description: cumulated revenue made by order splitted by date
       - name: quantity
         description: quantity of products bought by orders & date
       - name: purchase_costs
         description: costs of sending the products by orders & date
       - name: margin
         description: calculated margin based on the revenu * quantity
   - name: int_orders_operational
     description: new table to calculate the operational margin based on the previous table
     columns:
       - name: orders_id
         description: number chain to define an order made by a customer
         tests:
           - unique
           - not_null
       - name: date_date
         description: day the client has ordered
       - name: quantity
         description: quantity of products that has been ordered for each order
       - name: operational_margin
         description: operational margin that has been calculated based on previous tables
   - name: int_sales_margin
     description: shipping & purchase costs are in this table
     columns:
       - name: orders_id
         description: number chain to define an order made by a customer
       - name: date_date
         description: day the order has been made
       - name: products_id
         description: id of the product that has been orderred
       - name: revenue
         description: revenue generated by the order
       - name: quantity
         description: quantity of product that have been ordered
       - name: purchse_price
         description: prix d'achat
       - name: purchase_costs
         description: coûts d'achat du produit
       - name: margin
         description: net margin for the company
   - name: merged_ads_regie
     description: merged data from marketing & digital acquisition campaigns
     columns:
       - name: date_date
         description: day of the data
       - name: test_primary
         description: concatenation de date_date et de campaign_key 
       - name: paid_source
         description: source of acquisition, could be either FB, Criteo, GAds or Bing
       - name: campaign_key
         description: Id of the ongoing campaign
       - name: campaign_name
         description: string value witht the campaign name respecting the following template [country] [source] [goal] [random_name]
       - name: ads_cost
         description: details of the daily depenses for this campaign
       - name: impression
         description: number of impression made on the day for a specific campaign
       - name: click
         description: number of clics made on a daily basis for a specific campaign
   - name: merged_ads_with_unique_id
     description: merged data from marketing & digital acquisition campaigns
     columns:  
       - name: test_primary
         test: 
          - unique
          -  not_null